[package]
name = "key-server"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "key-server"
path = "src/server.rs"

[[bin]]
name = "aggregator-server"
path = "src/aggregator/server.rs"

[dependencies]
crypto = { path = "../crypto" }
seal-sdk = { path = "../seal-sdk" }
seal-committee = { path = "../seal-committee" }

fastcrypto.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
bcs.workspace = true
tracing.workspace = true
sui_types.workspace = true
mysten-service.workspace = true
sui_sdk.workspace = true
shared_crypto.workspace = true
move-core-types.workspace = true
semver.workspace = true
tokio.workspace = true
axum.workspace = true
tower-http.workspace = true
futures.workspace = true
anyhow.workspace = true
once_cell.workspace = true
serde_yaml.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde_with = { workspace = true, features = ["base64"] }
prometheus_closure_metric.workspace = true
prometheus.workspace = true
snap.workspace = true
git-version.workspace = true
tonic.workspace = true
prost-types.workspace = true

tap = "1.0.1"
duration-str = "0.17.0"
moka = { version = "0.12.15", features = ["sync"] }
hostname = "0.4"
hyper-util = "0.1.10"
http-body-util = "0.1.2"

sui-sdk-types.workspace = true
sui-rpc.workspace = true
sui-rpc-api.workspace = true
mvr_types = { git = "https://github.com/MystenLabs/mvr", rev = "b4771074967c733edd3a8e09611a40e1c181d84a", package = "mvr-types" }

[dev-dependencies]
tracing-test = "0.2.5"
test-cluster = { workspace = true }
sui-move-build = { workspace = true }
move-package-alt = { workspace = true }
temp-env = { version = "0.3", features = ["async_closure"] }
fastcrypto-tbls = { workspace = true }
wiremock = "0.5"